#!/usr/bin/env python3
import pygame
import sys
filepath = sys.argv[1]
pygame.init()
pygame.mixer.music.load(filepath)
pygame.mixer.music.play()
while pygame.mixer.music.get_busy():
    pygame.time.wait(1000)